- name: Deploys VM based on cloud image
  hosts: vmhosts 
  gather_facts: yes
  become: yes
  vars:
    vmnames:
      - devnode1
      - devnode2
  tasks:
    - name: provision kvm nodes
      include_role:
        name: vmspawn
      vars:
        pool_home: "{{ pool_dir }}"
        vm_names: "{{ vmnames }}"
        vm_vcpus: "{{ vcpus }}"
        vm_ram_mb: "{{ ram_mb }}"
        vm_user: "{{ user_name }}"
        vm_ssh_key: "{{ ssh_pub_key }}"
        vm_image_size: "{{ disk_size_gb }}"
